# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self


variables:
  tag: '$(Build.BuildId)'
  image: '$(dockerNamespace)/nodejsapp'



stages:
- stage: DockerHubLogin
  displayName: Docker Hub Login
  jobs:  
  - job: DockerHubLogin
    displayName: Docker Hub Login
    steps:
    - script: docker login -u $(dockerId) -p $(dockerPass)

- stage: Buildingtheimage
  displayName: Building image
  jobs:  
  - job: Buildingtheimage
    displayName: Building the docker image
    steps:
    - script: docker build -t $(image) $(Build.SourcesDirectory)

- stage: Taggingtheimage
  displayName: Tag the image
  jobs:  
  - job: Taggingtheimage
    displayName: Tag the docker image
    steps:
    - script: docker tag $(image) $(image):$(tag)

- stage: Pushtheimage
  displayName: Push the image to Docker Hub
  jobs:  
  - job: Pushtheimage
    displayName: Push the docker image to Docker Hub
    steps:
    - script: docker push $(image):$(tag)